import { backendClient } from './backendClient'

export const GetGitConflictPending = () => backendClient.invoke<boolean>('GetGitConflictPending')
export const ResolveGitConflict = (useLocal: boolean) => backendClient.invoke<void>('ResolveGitConflict', useLocal)
export const SetSkippedUpdateVersion = (version: string) => backendClient.invoke<void>('SetSkippedUpdateVersion', version)

export const BackupNow = () => backendClient.invoke<void>('BackupNow')
export const GetConfig = () => backendClient.invoke<any>('GetConfig')
export const GetLastBackupChanges = () => backendClient.invoke<any[]>('GetLastBackupChanges')
export const GetLastBackupCompletedAt = () => backendClient.invoke<string>('GetLastBackupCompletedAt')
export const RestoreFromCloud = () => backendClient.invoke<void>('RestoreFromCloud')

export const ListSkills = () => backendClient.invoke<any[]>('ListSkills')
export const ListCategories = () => backendClient.invoke<string[]>('ListCategories')
export const MoveSkillCategory = (skillID: string, category: string) => backendClient.invoke<void>('MoveSkillCategory', skillID, category)
export const DeleteSkill = (skillID: string) => backendClient.invoke<void>('DeleteSkill', skillID)
export const DeleteSkills = (skillIDs: string[]) => backendClient.invoke<void>('DeleteSkills', skillIDs)
export const ImportLocal = (dir: string, category: string) => backendClient.invoke<any>('ImportLocal', dir, category)
export const UpdateSkill = (skillID: string) => backendClient.invoke<void>('UpdateSkill', skillID)
export const CheckUpdates = () => backendClient.invoke<void>('CheckUpdates')
export const GetSkillMeta = (skillID: string) => backendClient.invoke<any>('GetSkillMeta', skillID)
export const GetSkillMetaByPath = (path: string) => backendClient.invoke<any>('GetSkillMetaByPath', path)
export const ReadSkillFileContent = (path: string) => backendClient.invoke<string>('ReadSkillFileContent', path)
export const SaveConfig = (cfg: any) => backendClient.invoke<void>('SaveConfig', cfg)
export const CheckMissingAgentPushDirs = (agentNames: string[]) => backendClient.invoke<any[]>('CheckMissingAgentPushDirs', agentNames)
export const PushToAgents = (skillIDs: string[], agentNames: string[]) => backendClient.invoke<any[]>('PushToAgents', skillIDs, agentNames)
export const PushToAgentsForce = (skillIDs: string[], agentNames: string[]) => backendClient.invoke<void>('PushToAgentsForce', skillIDs, agentNames)
export const CreateCategory = (name: string) => backendClient.invoke<void>('CreateCategory', name)
export const RenameCategory = (oldName: string, newName: string) => backendClient.invoke<void>('RenameCategory', oldName, newName)
export const DeleteCategory = (name: string) => backendClient.invoke<void>('DeleteCategory', name)

export const GetEnabledAgents = () => backendClient.invoke<any[]>('GetEnabledAgents')
export const GetAgentMemoryPreview = (agentName: string) => backendClient.invoke<any>('GetAgentMemoryPreview', agentName)
export const ListAgentSkills = (agentName: string) => backendClient.invoke<any[]>('ListAgentSkills', agentName)
export const ListManagedAgentSkills = (agentName: string) => backendClient.invoke<any[]>('ListManagedAgentSkills', agentName)
export const ListAllAgentSkills = () => backendClient.invoke<any[]>('ListAllAgentSkills')
export const DeleteAgentSkill = (agentName: string, skillPath: string) => backendClient.invoke<void>('DeleteAgentSkill', agentName, skillPath)
export const ScanAgentSkills = (agentName: string) => backendClient.invoke<any[]>('ScanAgentSkills', agentName)
export const PullFromAgent = (agentName: string, skillPaths: string[], category: string) => backendClient.invoke<any[]>('PullFromAgent', agentName, skillPaths, category)
export const PullFromAgentForce = (agentName: string, skillPaths: string[], category: string) => backendClient.invoke<void>('PullFromAgentForce', agentName, skillPaths, category)
export const CreateAgentSkillGroup = (name: string) => backendClient.invoke<void>('CreateAgentSkillGroup', name)
export const RenameAgentSkillGroup = (oldName: string, newName: string) => backendClient.invoke<void>('RenameAgentSkillGroup', oldName, newName)
export const DeleteAgentSkillGroup = (name: string) => backendClient.invoke<void>('DeleteAgentSkillGroup', name)
export const AssignAgentSkillGroup = (skillName: string, groupName: string) => backendClient.invoke<void>('AssignAgentSkillGroup', skillName, groupName)
export const ClearAgentSkillGroup = (skillName: string) => backendClient.invoke<void>('ClearAgentSkillGroup', skillName)
export const SetAgentSkillEnabled = (agentName: string, skillName: string, enabled: boolean) => backendClient.invoke<void>('SetAgentSkillEnabled', agentName, skillName, enabled)
export const SetAgentSkillGroupEnabled = (agentName: string, groupName: string, enabled: boolean) => backendClient.invoke<void>('SetAgentSkillGroupEnabled', agentName, groupName, enabled)

export const CreateModuleMemory = (name: string, content: string) => backendClient.invoke<any>('CreateModuleMemory', name, content)
export const DeleteModuleMemory = (name: string) => backendClient.invoke<void>('DeleteModuleMemory', name)
export const GetAllMemoryPushConfigs = () => backendClient.invoke<any[]>('GetAllMemoryPushConfigs')
export const GetAllMemoryPushStatuses = () => backendClient.invoke<any[]>('GetAllMemoryPushStatuses')
export const GetMainMemory = () => backendClient.invoke<any>('GetMainMemory')
export const ListModuleMemories = () => backendClient.invoke<any[]>('ListModuleMemories')
export const PushSelectedMemory = (agentTypes: string[], moduleNames: string[], mode: string) => backendClient.invoke<any[]>('PushSelectedMemory', agentTypes, moduleNames, mode)
export const SaveMainMemory = (content: string) => backendClient.invoke<any>('SaveMainMemory', content)
export const SaveMemoryPushConfig = (agentType: string, mode: string, autoPush: boolean) => backendClient.invoke<void>('SaveMemoryPushConfig', agentType, mode, autoPush)
export const SaveModuleMemory = (name: string, content: string) => backendClient.invoke<any>('SaveModuleMemory', name, content)
export const SetModuleMemoryEnabled = (name: string, enabled: boolean) => backendClient.invoke<any>('SetModuleMemoryEnabled', name, enabled)

export const CancelImportPrompts = (sessionID: string) => backendClient.invoke<void>('CancelImportPrompts', sessionID)
export const CompleteImportPrompts = (sessionID: string, overwriteNames: string[]) => backendClient.invoke<number>('CompleteImportPrompts', sessionID, overwriteNames)
export const CreatePrompt = (name: string, description: string, category: string, content: string, imageURLs: string[], webLinksMarkdown: string) => backendClient.invoke<any>('CreatePrompt', name, description, category, content, imageURLs, webLinksMarkdown)
export const DeletePrompt = (name: string) => backendClient.invoke<void>('DeletePrompt', name)
export const ListPromptCategories = () => backendClient.invoke<string[]>('ListPromptCategories')
export const ListPrompts = () => backendClient.invoke<any[]>('ListPrompts')
export const MovePromptCategory = (name: string, category: string) => backendClient.invoke<void>('MovePromptCategory', name, category)
export const UpdatePrompt = (originalName: string, name: string, description: string, category: string, content: string, imageURLs: string[], webLinksMarkdown: string) => backendClient.invoke<any>('UpdatePrompt', originalName, name, description, category, content, imageURLs, webLinksMarkdown)
export const CreatePromptCategory = (name: string) => backendClient.invoke<void>('CreatePromptCategory', name)
export const RenamePromptCategory = (oldName: string, newName: string) => backendClient.invoke<void>('RenamePromptCategory', oldName, newName)
export const DeletePromptCategory = (name: string) => backendClient.invoke<void>('DeletePromptCategory', name)

export const ListCloudProviders = () => backendClient.invoke<any[]>('ListCloudProviders')
export const TestProxyConnection = (targetURL: string, proxy: any) => backendClient.invoke<any>('TestProxyConnection', targetURL, proxy)
export const CheckAppUpdateAndNotify = () => backendClient.invoke<any>('CheckAppUpdateAndNotify')

export const ListStarredRepos = () => backendClient.invoke<any[]>('ListStarredRepos')
export const AddStarredRepo = (repoURL: string) => backendClient.invoke<any>('AddStarredRepo', repoURL)
export const AddStarredRepoWithCredentials = (repoURL: string, username: string, password: string) => backendClient.invoke<any>('AddStarredRepoWithCredentials', repoURL, username, password)
export const RemoveStarredRepo = (repoURL: string) => backendClient.invoke<void>('RemoveStarredRepo', repoURL)
export const UpdateStarredRepo = (repoURL: string) => backendClient.invoke<void>('UpdateStarredRepo', repoURL)
export const UpdateAllStarredRepos = () => backendClient.invoke<void>('UpdateAllStarredRepos')
export const ListAllStarSkills = () => backendClient.invoke<any[]>('ListAllStarSkills')
export const ListRepoStarSkills = (repoURL: string) => backendClient.invoke<any[]>('ListRepoStarSkills', repoURL)
export const ImportStarSkills = (skillPaths: string[], repoURL: string, category: string) => backendClient.invoke<void>('ImportStarSkills', skillPaths, repoURL, category)
export const PushStarSkillsToAgents = (skillPaths: string[], agentNames: string[]) => backendClient.invoke<any[]>('PushStarSkillsToAgents', skillPaths, agentNames)
export const PushStarSkillsToAgentsForce = (skillPaths: string[], agentNames: string[]) => backendClient.invoke<void>('PushStarSkillsToAgentsForce', skillPaths, agentNames)
