// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {main} from '../models';
import {config} from '../models';
import {agentskills} from '../models';
import {skills} from '../models';
import {shellsettings} from '../models';

export function AddCustomAgent(arg1:string,arg2:string):Promise<void>;

export function AddStarredRepo(arg1:string):Promise<domain.StarRepo>;

export function AddStarredRepoWithCredentials(arg1:string,arg2:string,arg3:string):Promise<domain.StarRepo>;

export function ApplyAppUpdate():Promise<void>;

export function AssignAgentSkillGroup(arg1:string,arg2:string):Promise<void>;

export function BackupNow():Promise<void>;

export function CancelImportPrompts(arg1:string):Promise<void>;

export function CheckAppUpdate():Promise<main.AppUpdateInfo>;

export function CheckAppUpdateAndNotify():Promise<main.AppUpdateInfo>;

export function CheckMissingAgentPushDirs(arg1:Array<string>):Promise<Array<domain.MissingPushDir>>;

export function CheckUpdates():Promise<void>;

export function ClearAgentSkillGroup(arg1:string):Promise<void>;

export function CompleteImportPrompts(arg1:string,arg2:Array<string>):Promise<number>;

export function CreateAgentSkillGroup(arg1:string):Promise<void>;

export function CreateCategory(arg1:string):Promise<void>;

export function CreateModuleMemory(arg1:string,arg2:string):Promise<main.ModuleMemoryDTO>;

export function CreatePrompt(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:string):Promise<domain.Prompt>;

export function CreatePromptCategory(arg1:string):Promise<void>;

export function DeleteAgentSkill(arg1:string,arg2:string):Promise<void>;

export function DeleteAgentSkillGroup(arg1:string):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteModuleMemory(arg1:string):Promise<void>;

export function DeletePrompt(arg1:string):Promise<void>;

export function DeletePromptCategory(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteSkills(arg1:Array<string>):Promise<void>;

export function DownloadAppUpdate(arg1:string):Promise<void>;

export function ExportPrompts():Promise<string>;

export function ExportPromptsByNames(arg1:Array<string>):Promise<string>;

export function GetAgentMemoryPreview(arg1:string):Promise<main.AgentMemoryPreviewDTO>;

export function GetAllMemoryPushConfigs():Promise<Array<main.MemoryPushConfigDTO>>;

export function GetAllMemoryPushStatuses():Promise<Array<main.PushStatusDTO>>;

export function GetAllModulePushTargets():Promise<Array<main.ModulePushTargetsDTO>>;

export function GetAppDataDir():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetBackendClientConfig():Promise<main.BackendClientConfig>;

export function GetConfig():Promise<config.AppConfig>;

export function GetEnabledAgents():Promise<Array<domain.AgentProfile>>;

export function GetGitConflictPending():Promise<boolean>;

export function GetLastBackupChanges():Promise<Array<domain.RemoteFile>>;

export function GetLastBackupCompletedAt():Promise<string>;

export function GetLogDir():Promise<string>;

export function GetMainMemory():Promise<main.MainMemoryDTO>;

export function GetMemoryPushConfig(arg1:string):Promise<main.MemoryPushConfigDTO>;

export function GetMemoryPushStatus(arg1:string):Promise<main.PushStatusDTO>;

export function GetModuleMemory(arg1:string):Promise<main.ModuleMemoryDTO>;

export function GetModulePushTargets(arg1:string):Promise<main.ModulePushTargetsDTO>;

export function GetSkillMeta(arg1:string):Promise<domain.SkillMeta>;

export function GetSkillMetaByPath(arg1:string):Promise<domain.SkillMeta>;

export function GetSkippedUpdateVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportLocal(arg1:string,arg2:string):Promise<domain.InstalledSkill>;

export function ImportPrompts():Promise<number>;

export function ImportStarSkills(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function ListAgentSkills(arg1:string):Promise<Array<domain.AgentSkillEntry>>;

export function ListAllAgentSkills():Promise<Array<agentskills.AllEntry>>;

export function ListAllStarSkills():Promise<Array<skills.StarSkillEntry>>;

export function ListCategories():Promise<Array<string>>;

export function ListCloudFiles():Promise<Array<domain.RemoteFile>>;

export function ListCloudProviders():Promise<Array<Record<string, any>>>;

export function ListManagedAgentSkills(arg1:string):Promise<Array<domain.ManagedAgentSkill>>;

export function ListModuleMemories():Promise<Array<main.ModuleMemoryDTO>>;

export function ListPromptCategories():Promise<Array<string>>;

export function ListPrompts():Promise<Array<domain.Prompt>>;

export function ListRepoStarSkills(arg1:string):Promise<Array<skills.StarSkillEntry>>;

export function ListSkills():Promise<Array<skills.InstalledSkillEntry>>;

export function ListStarredRepos():Promise<Array<domain.StarRepo>>;

export function MovePromptCategory(arg1:string,arg2:string):Promise<void>;

export function MoveSkillCategory(arg1:string,arg2:string):Promise<void>;

export function OpenAppDataDir():Promise<void>;

export function OpenFolderDialog(arg1:string):Promise<string>;

export function OpenGitBackupDir():Promise<void>;

export function OpenLogDir():Promise<void>;

export function OpenMemoryInEditor(arg1:string,arg2:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PrepareImportPrompts():Promise<main.PromptImportPrepareResult>;

export function PromptRootDir():Promise<string>;

export function PullFromAgent(arg1:string,arg2:Array<string>,arg3:string):Promise<Array<string>>;

export function PullFromAgentForce(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function PushAllMemory():Promise<Array<main.PushResultDTO>>;

export function PushMemoryToAgent(arg1:string):Promise<main.PushResultDTO>;

export function PushSelectedMemory(arg1:Array<string>,arg2:Array<string>,arg3:string):Promise<Array<main.PushResultDTO>>;

export function PushStarSkillsToAgents(arg1:Array<string>,arg2:Array<string>):Promise<Array<domain.PushConflict>>;

export function PushStarSkillsToAgentsForce(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function PushToAgents(arg1:Array<string>,arg2:Array<string>):Promise<Array<domain.PushConflict>>;

export function PushToAgentsForce(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function ReadSkillFileContent(arg1:string):Promise<string>;

export function RemoveCustomAgent(arg1:string):Promise<void>;

export function RemoveStarredRepo(arg1:string):Promise<void>;

export function RenameAgentSkillGroup(arg1:string,arg2:string):Promise<void>;

export function RenameCategory(arg1:string,arg2:string):Promise<void>;

export function RenamePromptCategory(arg1:string,arg2:string):Promise<void>;

export function ResolveGitConflict(arg1:boolean):Promise<void>;

export function RestoreFromCloud():Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function SaveMainMemory(arg1:string):Promise<main.MainMemoryDTO>;

export function SaveMemoryPushConfig(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveModuleMemory(arg1:string,arg2:string):Promise<main.ModuleMemoryDTO>;

export function SaveModulePushTargets(arg1:string,arg2:Array<string>):Promise<void>;

export function ScanAgentSkills(arg1:string):Promise<Array<domain.AgentSkillCandidate>>;

export function SetAgentSkillEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetAgentSkillGroupEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetModuleMemoryEnabled(arg1:string,arg2:boolean):Promise<main.ModuleMemoryDTO>;

export function SetSkippedUpdateVersion(arg1:string):Promise<void>;

export function TestProxyConnection(arg1:string,arg2:shellsettings.ProxyConfig):Promise<main.ProxyConnectionTestResult>;

export function UpdateAllStarredRepos():Promise<void>;

export function UpdatePrompt(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>,arg7:string):Promise<domain.Prompt>;

export function UpdateSkill(arg1:string):Promise<void>;

export function UpdateStarredRepo(arg1:string):Promise<void>;
