// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomTool(arg1, arg2) {
  return window['go']['main']['App']['AddCustomTool'](arg1, arg2);
}

export function BackupNow() {
  return window['go']['main']['App']['BackupNow']();
}

export function CheckUpdates() {
  return window['go']['main']['App']['CheckUpdates']();
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEnabledTools() {
  return window['go']['main']['App']['GetEnabledTools']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportLocal(arg1, arg2) {
  return window['go']['main']['App']['ImportLocal'](arg1, arg2);
}

export function InstallFromGitHub(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallFromGitHub'](arg1, arg2, arg3);
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListCloudFiles() {
  return window['go']['main']['App']['ListCloudFiles']();
}

export function ListCloudProviders() {
  return window['go']['main']['App']['ListCloudProviders']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function MoveSkillCategory(arg1, arg2) {
  return window['go']['main']['App']['MoveSkillCategory'](arg1, arg2);
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function PullFromTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['PullFromTool'](arg1, arg2, arg3);
}

export function PullFromToolForce(arg1, arg2, arg3) {
  return window['go']['main']['App']['PullFromToolForce'](arg1, arg2, arg3);
}

export function PushToTools(arg1, arg2) {
  return window['go']['main']['App']['PushToTools'](arg1, arg2);
}

export function PushToToolsForce(arg1, arg2) {
  return window['go']['main']['App']['PushToToolsForce'](arg1, arg2);
}

export function RemoveCustomTool(arg1) {
  return window['go']['main']['App']['RemoveCustomTool'](arg1);
}

export function RenameCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameCategory'](arg1, arg2);
}

export function RestoreFromCloud() {
  return window['go']['main']['App']['RestoreFromCloud']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanGitHub(arg1) {
  return window['go']['main']['App']['ScanGitHub'](arg1);
}

export function ScanToolSkills(arg1) {
  return window['go']['main']['App']['ScanToolSkills'](arg1);
}

export function UpdateSkill(arg1) {
  return window['go']['main']['App']['UpdateSkill'](arg1);
}
