// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {skill} from '../models';
import {install} from '../models';
import {backup} from '../models';

export function AddCustomTool(arg1:string,arg2:string):Promise<void>;

export function BackupNow():Promise<void>;

export function CheckUpdates():Promise<void>;

export function CreateCategory(arg1:string):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteSkills(arg1:Array<string>):Promise<void>;

export function GetConfig():Promise<config.AppConfig>;

export function GetEnabledTools():Promise<Array<config.ToolConfig>>;

export function Greet(arg1:string):Promise<string>;

export function ImportLocal(arg1:string,arg2:string):Promise<skill.Skill>;

export function InstallFromGitHub(arg1:string,arg2:Array<install.SkillCandidate>,arg3:string):Promise<void>;

export function ListCategories():Promise<Array<string>>;

export function ListCloudFiles():Promise<Array<backup.RemoteFile>>;

export function ListCloudProviders():Promise<Array<Record<string, any>>>;

export function ListSkills():Promise<Array<skill.Skill>>;

export function MoveSkillCategory(arg1:string,arg2:string):Promise<void>;

export function OpenFolderDialog():Promise<string>;

export function PullFromTool(arg1:string,arg2:Array<string>,arg3:string):Promise<Array<string>>;

export function PullFromToolForce(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function PushToTools(arg1:Array<string>,arg2:Array<string>):Promise<Array<string>>;

export function PushToToolsForce(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function RemoveCustomTool(arg1:string):Promise<void>;

export function RenameCategory(arg1:string,arg2:string):Promise<void>;

export function RestoreFromCloud():Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function ScanGitHub(arg1:string):Promise<Array<install.SkillCandidate>>;

export function ScanToolSkills(arg1:string):Promise<Array<skill.Skill>>;

export function UpdateSkill(arg1:string):Promise<void>;
